apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 --file docker-compose.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: crawler
  name: crawler
spec:
  ports:
  - name: "9151"
    port: 9151
    targetPort: 9151
  - name: "9555"
    port: 9555
    targetPort: 9555
  selector:
    io.kompose.service: crawler
status:
  loadBalancer: {}
