version: '3'
services:

  influxdb:
    image: influxdb:latest
    restart: always
    networks:
      monitor:
        ipv4_address: 172.28.1.2
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      # UDP Port
      - "8089:8089/udp"
    volumes:
      - ./influxdb/data:/var/lib/influxdb

  crawler:
    restart: on-failure
    image: nucypher-monitor:latest
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    command: ["crawl",
              "--influx-host", "172.28.1.2",
              "--provider", "http://52.53.253.85:8545",
              "--teacher", "https://discover.nucypher.network:9151"]
    networks:
      monitor:
        ipv4_address: 172.28.1.3
    volumes:
      - .:/code
      - "nucypher_datadir:/root/.local/share/nucypher"
    depends_on:
      - influxdb

  web:
    restart: on-failure
    image: nucypher-monitor:latest
    command: ["dashboard",
              "--debug",
              "--influx-host", "172.28.1.2",
              "--provider", "http://52.53.253.85:8545"]
    networks:
      monitor:
        ipv4_address: 172.28.1.4
    ports:
      - "12500:12500"
    volumes:
      - .:/code
      - "nucypher_datadir:/root/.local/share/nucypher"
    depends_on:
      - crawler
      - influxdb


networks:
  monitor:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
    nucypher_datadir:
