apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 --file docker-compose.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  ports:
  - name: "8086"
    port: 8086
    targetPort: 8086
  - name: "8082"
    port: 8082
    targetPort: 8082
  - name: "8089"
    port: 8089
    protocol: UDP
    targetPort: 8089
  selector:
    io.kompose.service: influxdb
status:
  loadBalancer: {}
