apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  containers:
    command: ["dashboard",
              "--debug",
              "--influx-host", "172.28.1.2",
              "--crawler-host", "172.28.1.3",
              "--provider", "${WEB3_PROVIDER_URI}",
              "--network", "${NUCYPHER_NETWORK}",
              "--tls-key-filepath", "/etc/letsencrypt/key.pem",
              "--certificate-filepath", "/etc/letsencrypt/fullchain.pem"]
    env:
      - name: WEB3_PROVIDER_URI
        valueFrom:
          configMapKeyRef:
            name: dashboard-config
            key: WEB3_PROVIDER_URI
      - name: NUCYPHER_NETWORK
        valueFrom:
          configMapKeyRef:
            name: dashboard-config
            key: NUCYPHER_NETWORK
    image: nucypher-monitor:latest
    name: web
    ports:
    - containerPort: 12500
    resources: {}
  restartPolicy: OnFailure
status: {}
